# Generated by Django 3.1.3 on 2020-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201207_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_details',
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, null=True),
        ),
    ]
