# Generated by Django 3.1.3 on 2020-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201207_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
    ]
