# Generated by Django 3.1.3 on 2020-12-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201214_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='created_at',
        ),
    ]
