# Generated by Django 3.1.3 on 2020-12-16 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20201215_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
