# Generated by Django 3.1.3 on 2021-01-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20201216_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='user_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
