# Generated by Django 3.1.3 on 2021-01-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210118_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
